# Generated by Django 5.1.2 on 2024-11-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="cars/media/uploads/"
            ),
        ),
    ]
